TEST: temporarily drop the number of extensions and disable e2e job

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -126,7 +126,7 @@ jobs:
 
 
 
-  # Pre-builds the amd64 version of the image for subsequent deploy e2e step
+  # Pre-builds the amd64 version of the image for a later deployment e2e step
   build:
     needs: [tags]
     runs-on: ubuntu-latest
@@ -158,85 +158,85 @@ jobs:
           cache-to: type=gha,mode=max,scope=taqasta-amd64,timeout=60m
 
   # Pre-build the image, deploy via compose and run e2e
-  deploy-e2e:
-    needs: [build]
-    timeout-minutes: 60
-    outputs:
-      pages_url: ${{ steps.deployment_pages.outputs.page_url }}
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push' || github.event_name == 'pull_request'
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Compile
-        run: bash compile.sh
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          install: true
-          platforms: linux/amd64
-
-      - name: Build and load
-        id: docker_build
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          platforms: linux/amd64
-          secrets: |
-            COMPOSER_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          push: false
-          tags: ${{ needs.tags.outputs.REGISTRY_TAGS }}
-          cache-from: type=gha,scope=taqasta-amd64,timeout=60m
-          cache-to: type=gha,mode=max,scope=taqasta-amd64,timeout=60m
-          load: true
-
-      - name: Set up environment
-        shell: bash
-        run: mv .env.ci .env
-
-      - name: Setup Docker Compose
-        env:
-          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DOCKER_BUILDKIT: 1
-        shell: bash
-        run: DOCKER_BUILDKIT=1 docker compose up -d
-
-      - name: Wait for init
-        shell: bash
-        run: while !  docker compose logs web --tail 10 | grep -q '>>>>> run-maintenance-script.sh <<<<<'; do sleep 1; done
-
-      - name: Wait for container to be healthy
-        shell: bash
-        run: while ! docker inspect --format='{{json .State.Health.Status}}' $(echo $(basename $(pwd)) | tr '[:upper:]' '[:lower:]')-web-1 | grep -q 'healthy'; do sleep 1; done
-
-      # todo, migrate to docker image? https://playwright.dev/docs/docker
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 20
-      - name: Install dependencies
-        working-directory: ./e2e
-        run: npm ci
-      - name: Install Playwright Browsers
-        working-directory: ./e2e
-        run: npx playwright install chromium --with-deps
-      - name: Run Playwright tests
-        working-directory: ./e2e
-        run: npx playwright test
-
-      - name: Upload screenshots as a github-pages artifact
-        uses: actions/upload-pages-artifact@v3
-        if: failure()
-        with:
-          name: playwright-report
-          path: e2e/playwright-report/
-          retention-days: 7
-
-      - name: Stop containers
-        if: always()
-        shell: bash
-        run: docker compose down --volumes --timeout 60
+#  deploy-e2e:
+#    needs: [build]
+#    timeout-minutes: 60
+#    outputs:
+#      pages_url: ${{ steps.deployment_pages.outputs.page_url }}
+#    runs-on: ubuntu-latest
+#    if: github.event_name == 'push' || github.event_name == 'pull_request'
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Compile
+#        run: bash compile.sh
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#        with:
+#          install: true
+#          platforms: linux/amd64
+#
+#      - name: Build and load
+#        id: docker_build
+#        uses: docker/build-push-action@v6
+#        with:
+#          context: .
+#          platforms: linux/amd64
+#          secrets: |
+#            COMPOSER_TOKEN=${{ secrets.GITHUB_TOKEN }}
+#          tags: ${{ needs.tags.outputs.REGISTRY_TAGS }}
+#          cache-from: type=gha,scope=taqasta-amd64,timeout=60m
+#          cache-to: type=gha,mode=max,scope=taqasta-amd64,timeout=60m
+#          push: false
+#          load: true
+#
+#      - name: Set up environment
+#        shell: bash
+#        run: mv .env.ci .env
+#
+#      - name: Setup Docker Compose
+#        env:
+#          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          DOCKER_BUILDKIT: 1
+#        shell: bash
+#        run: DOCKER_BUILDKIT=1 docker compose up -d
+#
+#      - name: Wait for init
+#        shell: bash
+#        run: while !  docker compose logs web --tail 10 | grep -q '>>>>> run-maintenance-script.sh <<<<<'; do sleep 1; done
+#
+#      - name: Wait for container to be healthy
+#        shell: bash
+#        run: while ! docker inspect --format='{{json .State.Health.Status}}' $(echo $(basename $(pwd)) | tr '[:upper:]' '[:lower:]')-web-1 | grep -q 'healthy'; do sleep 1; done
+#
+#      # todo, migrate to docker image? https://playwright.dev/docs/docker
+#      - uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#      - name: Install dependencies
+#        working-directory: ./e2e
+#        run: npm ci
+#      - name: Install Playwright Browsers
+#        working-directory: ./e2e
+#        run: npx playwright install chromium --with-deps
+#      - name: Run Playwright tests
+#        working-directory: ./e2e
+#        run: npx playwright test
+#
+#      - name: Upload screenshots as a github-pages artifact
+#        uses: actions/upload-pages-artifact@v3
+#        if: failure()
+#        with:
+#          name: playwright-report
+#          path: e2e/playwright-report/
+#          retention-days: 7
+#
+#      - name: Stop containers
+#        if: always()
+#        shell: bash
+#        run: docker compose down --volumes --timeout 60
 
   # Builds from cache & push the image to GitHub registry this time
   # see https://github.com/orgs/community/discussions/148648#discussioncomment-12144381 merge?
@@ -281,10 +281,10 @@ jobs:
           platforms: linux/${{ matrix.platform }}
           secrets: |
             COMPOSER_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          push: true
           tags: ${{ needs.tags.outputs.REGISTRY_TAGS }}
           cache-from: type=gha,scope=taqasta-${{ matrix.platform }},timeout=60m
           cache-to: type=gha,mode=max,scope=taqasta-${{ matrix.platform }},timeout=60m
+          push: true
       -
         name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
